<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="6" total="54" passed="35" failed="11" skipped="2">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-10-12T13:40:56Z" name="Suite" finished-at="2024-10-12T13:52:28Z" duration-ms="692145">
    <groups>
    </groups>
    <test started-at="2024-10-12T13:40:56Z" name="Test" finished-at="2024-10-12T13:52:28Z" duration-ms="692145">
      <class name="annotation.AnnotationCCC">
        <test-method is-config="true" signature="sampleBeforeSuiteAnnotationMethod()[pri:0, instance:annotation.AnnotationCCC@25aca718]" started-at="2024-10-12T13:40:56Z" name="sampleBeforeSuiteAnnotationMethod" finished-at="2024-10-12T13:40:56Z" duration-ms="16" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleBeforeSuiteAnnotationMethod -->
        <test-method is-config="true" signature="sampleBeforeClassAnnotationMethod()[pri:0, instance:annotation.AnnotationCCC@25aca718]" started-at="2024-10-12T13:41:03Z" name="sampleBeforeClassAnnotationMethod" finished-at="2024-10-12T13:41:03Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleBeforeClassAnnotationMethod -->
        <test-method is-config="true" signature="sampleBeforeMethodAnnotation()[pri:0, instance:annotation.AnnotationCCC@25aca718]" started-at="2024-10-12T13:41:03Z" name="sampleBeforeMethodAnnotation" finished-at="2024-10-12T13:41:03Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleBeforeMethodAnnotation -->
        <test-method signature="firstTestCase()[pri:0, instance:annotation.AnnotationCCC@25aca718]" started-at="2024-10-12T13:41:03Z" name="firstTestCase" finished-at="2024-10-12T13:41:03Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstTestCase -->
        <test-method is-config="true" signature="sampleAfterMethodAnnotation()[pri:0, instance:annotation.AnnotationCCC@25aca718]" started-at="2024-10-12T13:41:03Z" name="sampleAfterMethodAnnotation" finished-at="2024-10-12T13:41:03Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleAfterMethodAnnotation -->
        <test-method is-config="true" signature="sampleAfterClassAnnotationMethod()[pri:0, instance:annotation.AnnotationCCC@25aca718]" started-at="2024-10-12T13:41:03Z" name="sampleAfterClassAnnotationMethod" finished-at="2024-10-12T13:41:03Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleAfterClassAnnotationMethod -->
        <test-method is-config="true" signature="sampleAfterSuiteAnnotationMethod()[pri:0, instance:annotation.AnnotationCCC@25aca718]" started-at="2024-10-12T13:52:28Z" name="sampleAfterSuiteAnnotationMethod" finished-at="2024-10-12T13:52:28Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleAfterSuiteAnnotationMethod -->
      </class> <!-- annotation.AnnotationCCC -->
      <class name="brockenlink.FindStatusCodeOfLink">
        <test-method signature="sampleTestCase()[pri:0, instance:brockenlink.FindStatusCodeOfLink@2f1de2d6]" started-at="2024-10-12T13:41:02Z" name="sampleTestCase" finished-at="2024-10-12T13:41:03Z" duration-ms="681" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleTestCase -->
      </class> <!-- brockenlink.FindStatusCodeOfLink -->
      <class name="invocation.InvocationCountClass">
        <test-method signature="VerifyUserCanSendEmail()[pri:0, instance:invocation.InvocationCountClass@3a0baae5]" started-at="2024-10-12T13:41:03Z" name="VerifyUserCanSendEmail" finished-at="2024-10-12T13:41:03Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyUserCanSendEmail -->
        <test-method signature="VerifyUserCanSendEmail()[pri:0, instance:invocation.InvocationCountClass@3a0baae5]" started-at="2024-10-12T13:41:03Z" name="VerifyUserCanSendEmail" finished-at="2024-10-12T13:41:03Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyUserCanSendEmail -->
        <test-method signature="VerifyUserCanSendEmail()[pri:0, instance:invocation.InvocationCountClass@3a0baae5]" started-at="2024-10-12T13:41:03Z" name="VerifyUserCanSendEmail" finished-at="2024-10-12T13:41:03Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyUserCanSendEmail -->
        <test-method signature="VerifyUserCanSendEmail()[pri:0, instance:invocation.InvocationCountClass@3a0baae5]" started-at="2024-10-12T13:41:03Z" name="VerifyUserCanSendEmail" finished-at="2024-10-12T13:41:03Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyUserCanSendEmail -->
      </class> <!-- invocation.InvocationCountClass -->
      <class name="brockenlink.BrockenLinkClass">
        <test-method signature="sampleTestCase()[pri:0, instance:brockenlink.BrockenLinkClass@6a55299e]" started-at="2024-10-12T13:40:56Z" name="sampleTestCase" finished-at="2024-10-12T13:41:02Z" duration-ms="6045" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleTestCase -->
      </class> <!-- brockenlink.BrockenLinkClass -->
      <class name="assertions.SoftAssertionClass">
        <test-method signature="verifyUserCanLoginWithValidUserNameAndPassword()[pri:0, instance:assertions.SoftAssertionClass@71c27ee8]" started-at="2024-10-12T13:52:28Z" name="verifyUserCanLoginWithValidUserNameAndPassword" finished-at="2024-10-12T13:52:28Z" duration-ms="8" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
User name is not displayed expected [true] but found [false],
deleted user is displayed expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
User name is not displayed expected [true] but found [false],
deleted user is displayed expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at assertions.SoftAssertionClass.verifyUserCanLoginWithValidUserNameAndPassword(SoftAssertionClass.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserCanLoginWithValidUserNameAndPassword -->
        <test-method signature="verifyUserCanReadEmail()[pri:0, instance:assertions.SoftAssertionClass@71c27ee8]" started-at="2024-10-12T13:52:28Z" name="verifyUserCanReadEmail" finished-at="2024-10-12T13:52:28Z" duration-ms="0" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [null] but found [anno.AnnoClass@7e94d093]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [null] but found [anno.AnnoClass@7e94d093]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at assertions.SoftAssertionClass.verifyUserCanReadEmail(SoftAssertionClass.java:46)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserCanReadEmail -->
        <test-method signature="verifyUserCanSendEmail()[pri:0, instance:assertions.SoftAssertionClass@71c27ee8]" started-at="2024-10-12T13:52:28Z" name="verifyUserCanSendEmail" finished-at="2024-10-12T13:52:28Z" duration-ms="0" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
values is not matching expected [45] but found [23]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
values is not matching expected [45] but found [23]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at assertions.SoftAssertionClass.verifyUserCanSendEmail(SoftAssertionClass.java:36)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserCanSendEmail -->
      </class> <!-- assertions.SoftAssertionClass -->
      <class name="anno.AnnoClass">
        <test-method is-config="true" signature="sampleBeforeClassAnnotationMethod()[pri:0, instance:anno.AnnoClass@294a6b8e]" started-at="2024-10-12T13:48:24Z" name="sampleBeforeClassAnnotationMethod" finished-at="2024-10-12T13:48:24Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleBeforeClassAnnotationMethod -->
        <test-method is-config="true" signature="sampleBeforeMethodAnnotation()[pri:0, instance:anno.AnnoClass@294a6b8e]" started-at="2024-10-12T13:48:24Z" name="sampleBeforeMethodAnnotation" finished-at="2024-10-12T13:48:24Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleBeforeMethodAnnotation -->
        <test-method is-config="true" signature="sampleBeforeMethodAnnotation()[pri:0, instance:anno.AnnoClass@294a6b8e]" started-at="2024-10-12T13:48:24Z" name="sampleBeforeMethodAnnotation" finished-at="2024-10-12T13:48:24Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleBeforeMethodAnnotation -->
        <test-method signature="A()[pri:0, instance:anno.AnnoClass@294a6b8e]" started-at="2024-10-12T13:48:24Z" name="A" finished-at="2024-10-12T13:48:24Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- A -->
        <test-method signature="B()[pri:0, instance:anno.AnnoClass@294a6b8e]" started-at="2024-10-12T13:48:24Z" name="B" finished-at="2024-10-12T13:48:24Z" duration-ms="8" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- B -->
        <test-method is-config="true" signature="sampleAfterMethodAnnotation()[pri:0, instance:anno.AnnoClass@294a6b8e]" started-at="2024-10-12T13:48:24Z" name="sampleAfterMethodAnnotation" finished-at="2024-10-12T13:48:24Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleAfterMethodAnnotation -->
        <test-method is-config="true" signature="sampleAfterClassAnnotationMethod()[pri:0, instance:anno.AnnoClass@294a6b8e]" started-at="2024-10-12T13:48:24Z" name="sampleAfterClassAnnotationMethod" finished-at="2024-10-12T13:48:24Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleAfterClassAnnotationMethod -->
        <test-method is-config="true" signature="sampleAfterMethodAnnotation()[pri:0, instance:anno.AnnoClass@294a6b8e]" started-at="2024-10-12T13:48:24Z" name="sampleAfterMethodAnnotation" finished-at="2024-10-12T13:48:24Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleAfterMethodAnnotation -->
      </class> <!-- anno.AnnoClass -->
      <class name="annotation.AnnotationInTestNg">
        <test-method is-config="true" signature="samplebeforeTestAnnotation()[pri:0, instance:annotation.AnnotationInTestNg@16fdec90]" started-at="2024-10-12T13:40:56Z" name="samplebeforeTestAnnotation" finished-at="2024-10-12T13:40:56Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- samplebeforeTestAnnotation -->
        <test-method is-config="true" signature="sampleBeforeTestAnnotationMethod()[pri:0, instance:annotation.AnnotationCCC@25aca718]" started-at="2024-10-12T13:40:56Z" name="sampleBeforeTestAnnotationMethod" finished-at="2024-10-12T13:40:56Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleBeforeTestAnnotationMethod -->
        <test-method is-config="true" signature="samplebeforeclassAnnotation()[pri:0, instance:annotation.AnnotationInTestNg@16fdec90]" started-at="2024-10-12T13:40:56Z" name="samplebeforeclassAnnotation" finished-at="2024-10-12T13:40:56Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- samplebeforeclassAnnotation -->
        <test-method is-config="true" signature="samplebeforemethodAnnotation()[pri:0, instance:annotation.AnnotationInTestNg@16fdec90]" started-at="2024-10-12T13:40:56Z" name="samplebeforemethodAnnotation" finished-at="2024-10-12T13:40:56Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- samplebeforemethodAnnotation -->
        <test-method signature="VerifyUserCanReadEmail()[pri:0, instance:annotation.AnnotationInTestNg@16fdec90]" started-at="2024-10-12T13:40:56Z" name="VerifyUserCanReadEmail" finished-at="2024-10-12T13:40:56Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyUserCanReadEmail -->
        <test-method signature="VerifyUserCanSendEmail()[pri:0, instance:annotation.AnnotationInTestNg@16fdec90]" started-at="2024-10-12T13:40:56Z" name="VerifyUserCanSendEmail" finished-at="2024-10-12T13:40:56Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyUserCanSendEmail -->
        <test-method is-config="true" signature="sampleaftermethodAnnotation()[pri:0, instance:annotation.AnnotationInTestNg@16fdec90]" started-at="2024-10-12T13:40:56Z" name="sampleaftermethodAnnotation" finished-at="2024-10-12T13:40:56Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleaftermethodAnnotation -->
        <test-method is-config="true" signature="samplebeforemethodAnnotation()[pri:0, instance:annotation.AnnotationInTestNg@16fdec90]" started-at="2024-10-12T13:40:56Z" name="samplebeforemethodAnnotation" finished-at="2024-10-12T13:40:56Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- samplebeforemethodAnnotation -->
        <test-method is-config="true" signature="sampleaftermethodAnnotation()[pri:0, instance:annotation.AnnotationInTestNg@16fdec90]" started-at="2024-10-12T13:40:56Z" name="sampleaftermethodAnnotation" finished-at="2024-10-12T13:40:56Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleaftermethodAnnotation -->
        <test-method signature="verifyUserCanLoginWithValidusernameandPassward()[pri:0, instance:annotation.AnnotationInTestNg@16fdec90]" started-at="2024-10-12T13:40:56Z" name="verifyUserCanLoginWithValidusernameandPassward" finished-at="2024-10-12T13:40:56Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserCanLoginWithValidusernameandPassward -->
        <test-method is-config="true" signature="samplebeforemethodAnnotation()[pri:0, instance:annotation.AnnotationInTestNg@16fdec90]" started-at="2024-10-12T13:40:56Z" name="samplebeforemethodAnnotation" finished-at="2024-10-12T13:40:56Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- samplebeforemethodAnnotation -->
        <test-method is-config="true" signature="sampleaftermethodAnnotation()[pri:0, instance:annotation.AnnotationInTestNg@16fdec90]" started-at="2024-10-12T13:40:56Z" name="sampleaftermethodAnnotation" finished-at="2024-10-12T13:40:56Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleaftermethodAnnotation -->
        <test-method is-config="true" signature="sampleAfterclassAnnotation()[pri:0, instance:annotation.AnnotationInTestNg@16fdec90]" started-at="2024-10-12T13:40:56Z" name="sampleAfterclassAnnotation" finished-at="2024-10-12T13:40:56Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleAfterclassAnnotation -->
        <test-method is-config="true" signature="sampleAfterTestAnnotation()[pri:0, instance:annotation.AnnotationInTestNg@16fdec90]" started-at="2024-10-12T13:52:28Z" name="sampleAfterTestAnnotation" finished-at="2024-10-12T13:52:28Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleAfterTestAnnotation -->
        <test-method is-config="true" signature="sampleAfterTestAnnotationMethod()[pri:0, instance:annotation.AnnotationCCC@25aca718]" started-at="2024-10-12T13:52:28Z" name="sampleAfterTestAnnotationMethod" finished-at="2024-10-12T13:52:28Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleAfterTestAnnotationMethod -->
      </class> <!-- annotation.AnnotationInTestNg -->
      <class name="data_provider_annotation.DataProvideClass">
        <test-method signature="verifyUserCanLoginWithProvidedCredentials([Ljava.lang.String;)[pri:0, instance:data_provider_annotation.DataProvideClass@4eb386df]" started-at="2024-10-12T13:41:03Z" name="verifyUserCanLoginWithProvidedCredentials" data-provider="credentials" finished-at="2024-10-12T13:41:03Z" duration-ms="2" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[Ljava.lang.String;@6da9dc6]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserCanLoginWithProvidedCredentials -->
        <test-method signature="verifyUserCanLoginWithProvidedCredentials([Ljava.lang.String;)[pri:0, instance:data_provider_annotation.DataProvideClass@4eb386df]" started-at="2024-10-12T13:41:03Z" name="verifyUserCanLoginWithProvidedCredentials" data-provider="credentials" finished-at="2024-10-12T13:41:03Z" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[Ljava.lang.String;@7fd69dd]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserCanLoginWithProvidedCredentials -->
        <test-method signature="verifyUserCanLoginWithProvidedCredentials([Ljava.lang.String;)[pri:0, instance:data_provider_annotation.DataProvideClass@4eb386df]" started-at="2024-10-12T13:41:03Z" name="verifyUserCanLoginWithProvidedCredentials" data-provider="credentials" finished-at="2024-10-12T13:41:03Z" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[Ljava.lang.String;@12010fd1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserCanLoginWithProvidedCredentials -->
        <test-method signature="verifyUserCanLoginWithProvidedCredentials2(java.lang.String, java.lang.String)[pri:0, instance:data_provider_annotation.DataProvideClass@4eb386df]" started-at="2024-10-12T13:41:03Z" name="verifyUserCanLoginWithProvidedCredentials2" data-provider="credentials" finished-at="2024-10-12T13:41:03Z" duration-ms="2" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Ajay]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Ajay@123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserCanLoginWithProvidedCredentials2 -->
        <test-method signature="verifyUserCanLoginWithProvidedCredentials2(java.lang.String, java.lang.String)[pri:0, instance:data_provider_annotation.DataProvideClass@4eb386df]" started-at="2024-10-12T13:41:03Z" name="verifyUserCanLoginWithProvidedCredentials2" data-provider="credentials" finished-at="2024-10-12T13:41:03Z" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Sanjay]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Sanjay@345]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserCanLoginWithProvidedCredentials2 -->
        <test-method signature="verifyUserCanLoginWithProvidedCredentials2(java.lang.String, java.lang.String)[pri:0, instance:data_provider_annotation.DataProvideClass@4eb386df]" started-at="2024-10-12T13:41:03Z" name="verifyUserCanLoginWithProvidedCredentials2" data-provider="credentials" finished-at="2024-10-12T13:41:03Z" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Amar]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Am&4567]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserCanLoginWithProvidedCredentials2 -->
        <test-method signature="verifyuserCanaddDataOnUI(java.lang.String)[pri:0, instance:data_provider_annotation.DataProvideClass@4eb386df]" started-at="2024-10-12T13:41:03Z" name="verifyuserCanaddDataOnUI" data-provider="getUserName" finished-at="2024-10-12T13:41:03Z" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[ABC]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyuserCanaddDataOnUI -->
        <test-method signature="verifyuserCanaddDataOnUI(java.lang.String)[pri:0, instance:data_provider_annotation.DataProvideClass@4eb386df]" started-at="2024-10-12T13:41:03Z" name="verifyuserCanaddDataOnUI" data-provider="getUserName" finished-at="2024-10-12T13:41:03Z" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[PQR]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyuserCanaddDataOnUI -->
        <test-method signature="verifyuserCanaddDataOnUI(java.lang.String)[pri:0, instance:data_provider_annotation.DataProvideClass@4eb386df]" started-at="2024-10-12T13:41:03Z" name="verifyuserCanaddDataOnUI" data-provider="getUserName" finished-at="2024-10-12T13:41:03Z" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[GTR]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyuserCanaddDataOnUI -->
        <test-method signature="verifyuserCanaddDataOnUI(java.lang.String)[pri:0, instance:data_provider_annotation.DataProvideClass@4eb386df]" started-at="2024-10-12T13:41:03Z" name="verifyuserCanaddDataOnUI" data-provider="getUserName" finished-at="2024-10-12T13:41:03Z" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[KJU]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyuserCanaddDataOnUI -->
        <test-method signature="verifyuserCanaddDataOnUI(java.lang.String)[pri:0, instance:data_provider_annotation.DataProvideClass@4eb386df]" started-at="2024-10-12T13:41:03Z" name="verifyuserCanaddDataOnUI" data-provider="getUserName" finished-at="2024-10-12T13:41:03Z" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[hytff]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyuserCanaddDataOnUI -->
      </class> <!-- data_provider_annotation.DataProvideClass -->
      <class name="selenium.FileUploadTestCase2">
        <test-method signature="verifyfileupload()[pri:0, instance:selenium.FileUploadTestCase2@77825085]" started-at="2024-10-12T13:48:24Z" name="verifyfileupload" finished-at="2024-10-12T13:51:15Z" duration-ms="171127" status="FAIL">
          <exception class="org.openqa.selenium.TimeoutException">
            <message>
              <![CDATA[Expected condition failed: waiting for visibility of all elements located by By.xpath: //h3[@id='res']/center (tried for 5 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.8.0', revision: '924c4067df', time: '2017-11-30T11:20:39.408Z'
System info: host: 'LAPTOP-4JQ0QDCA', ip: '192.168.83.94', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '22.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 129.0.6668.100, chrome: {chromedriverVersion: 128.0.6613.119 (6e439cfca4d..., userDataDir: C:\Users\SSWOR\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:54842}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 9615e2dd3163de704809cad2084bbb65]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of all elements located by By.xpath: //h3[@id='res']/center (tried for 5 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.8.0', revision: '924c4067df', time: '2017-11-30T11:20:39.408Z'
System info: host: 'LAPTOP-4JQ0QDCA', ip: '192.168.83.94', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '22.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 129.0.6668.100, chrome: {chromedriverVersion: 128.0.6613.119 (6e439cfca4d..., userDataDir: C:\Users\SSWOR\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:54842}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 9615e2dd3163de704809cad2084bbb65
at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:82)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231)
at selenium.FileUploadTestCase2.verifyfileupload(FileUploadTestCase2.java:61)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.TimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyfileupload -->
      </class> <!-- selenium.FileUploadTestCase2 -->
      <class name="enables.EnablesInTestNg">
        <test-method signature="A()[pri:0, instance:enables.EnablesInTestNg@79517588]" started-at="2024-10-12T13:41:03Z" name="A" finished-at="2024-10-12T13:41:03Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- A -->
      </class> <!-- enables.EnablesInTestNg -->
      <class name="selenium.FileUploadTestCase">
        <test-method signature="verifyfileupload()[pri:0, instance:selenium.FileUploadTestCase@7ac0e420]" started-at="2024-10-12T13:41:03Z" name="verifyfileupload" finished-at="2024-10-12T13:41:36Z" duration-ms="33466" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyfileupload -->
      </class> <!-- selenium.FileUploadTestCase -->
      <class name="dependent.Depedent_test_case_class2">
        <test-method signature="verifyUserCanLoginWithValidusernameandPassward()[pri:0, instance:dependent.Depedent_test_case_class2@1b835480]" started-at="2024-10-12T13:51:15Z" name="verifyUserCanLoginWithValidusernameandPassward" finished-at="2024-10-12T13:51:15Z" duration-ms="0" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at dependent.Depedent_test_case_class2.verifyUserCanLoginWithValidusernameandPassward(Depedent_test_case_class2.java:11)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserCanLoginWithValidusernameandPassward -->
      </class> <!-- dependent.Depedent_test_case_class2 -->
      <class name="brockenlink.BrockenLinkClass2">
        <test-method signature="sampleTestCase()[pri:0, instance:brockenlink.BrockenLinkClass2@6fb365ed]" started-at="2024-10-12T13:52:23Z" name="sampleTestCase" finished-at="2024-10-12T13:52:28Z" duration-ms="5590" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleTestCase -->
      </class> <!-- brockenlink.BrockenLinkClass2 -->
      <class name="annotation.FileUploadTestCase">
        <test-method signature="verifyfileupload()[pri:0, instance:annotation.FileUploadTestCase@289710d9]" started-at="2024-10-12T13:41:36Z" name="verifyfileupload" finished-at="2024-10-12T13:42:15Z" duration-ms="38844" status="FAIL">
          <exception class="org.openqa.selenium.TimeoutException">
            <message>
              <![CDATA[Expected condition failed: waiting for visibility of all elements located by By.xpath: //h3[@id='res']/center (tried for 5 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.8.0', revision: '924c4067df', time: '2017-11-30T11:20:39.408Z'
System info: host: 'LAPTOP-4JQ0QDCA', ip: '192.168.83.94', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '22.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 129.0.6668.100, chrome: {chromedriverVersion: 128.0.6613.119 (6e439cfca4d..., userDataDir: C:\Users\SSWOR\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:54293}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: e4dc594415722448f886b7373ac1e3d3]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of all elements located by By.xpath: //h3[@id='res']/center (tried for 5 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.8.0', revision: '924c4067df', time: '2017-11-30T11:20:39.408Z'
System info: host: 'LAPTOP-4JQ0QDCA', ip: '192.168.83.94', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '22.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 129.0.6668.100, chrome: {chromedriverVersion: 128.0.6613.119 (6e439cfca4d..., userDataDir: C:\Users\SSWOR\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:54293}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: e4dc594415722448f886b7373ac1e3d3
at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:82)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231)
at annotation.FileUploadTestCase.verifyfileupload(FileUploadTestCase.java:60)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.TimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyfileupload -->
      </class> <!-- annotation.FileUploadTestCase -->
      <class name="dependent.Depedent_test_case_class3">
        <test-method signature="verifyUserCanLoginWithValidusernameandPassward()[pri:0, instance:dependent.Depedent_test_case_class3@4b1d6571]" started-at="2024-10-12T13:48:24Z" name="verifyUserCanLoginWithValidusernameandPassward" finished-at="2024-10-12T13:48:24Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserCanLoginWithValidusernameandPassward -->
      </class> <!-- dependent.Depedent_test_case_class3 -->
      <class name="screen.cpature.ScreenCaptureClass2">
        <test-method signature="sampleTestCase()[pri:0, instance:screen.cpature.ScreenCaptureClass2@5a18cd76]" started-at="2024-10-12T13:42:15Z" name="sampleTestCase" finished-at="2024-10-12T13:42:52Z" duration-ms="36441" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at screen.cpature.ScreenCaptureClass2.sampleTestCase(ScreenCaptureClass2.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleTestCase -->
        <test-method is-config="true" signature="afterMethodForScreenCapture(org.testng.ITestResult)[pri:0, instance:screen.cpature.ScreenCaptureClass2@5a18cd76]" started-at="2024-10-12T13:42:52Z" name="afterMethodForScreenCapture" finished-at="2024-10-12T13:42:52Z" duration-ms="130" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=sampleTestCase status=FAILURE method=ScreenCaptureClass2.sampleTestCase()[pri:0, instance:screen.cpature.ScreenCaptureClass2@5a18cd76] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethodForScreenCapture -->
      </class> <!-- screen.cpature.ScreenCaptureClass2 -->
      <class name="assertions.AssertionClass">
        <test-method signature="verifyUserCanLoginWithValidUserNameAndPassword()[pri:0, instance:assertions.AssertionClass@1afdd473]" started-at="2024-10-12T13:40:56Z" name="verifyUserCanLoginWithValidUserNameAndPassword" finished-at="2024-10-12T13:40:56Z" duration-ms="8" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserCanLoginWithValidUserNameAndPassword -->
        <test-method signature="verifyUserCanReadEmail()[pri:0, instance:assertions.AssertionClass@1afdd473]" started-at="2024-10-12T13:40:56Z" name="verifyUserCanReadEmail" finished-at="2024-10-12T13:40:56Z" duration-ms="3" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Current share price is not matching expected [405.55] but found [405.55]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Current share price is not matching expected [405.55] but found [405.55]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at assertions.AssertionClass.verifyUserCanReadEmail(AssertionClass.java:45)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserCanReadEmail -->
        <test-method signature="verifyUserCanSendEmail()[pri:0, instance:assertions.AssertionClass@1afdd473]" started-at="2024-10-12T13:40:56Z" name="verifyUserCanSendEmail" finished-at="2024-10-12T13:40:56Z" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [null] but found [anno.AnnoClass@1d470d0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [null] but found [anno.AnnoClass@1d470d0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotSame(Assert.java:772)
at org.testng.Assert.assertNull(Assert.java:708)
at org.testng.Assert.assertNull(Assert.java:697)
at assertions.AssertionClass.verifyUserCanSendEmail(AssertionClass.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserCanSendEmail -->
        <test-method signature="verifyuserslist()[pri:0, instance:assertions.AssertionClass@1afdd473]" started-at="2024-10-12T13:40:56Z" name="verifyuserslist" finished-at="2024-10-12T13:40:56Z" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [45] but found [23]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [45] but found [23]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at assertions.AssertionClass.verifyuserslist(AssertionClass.java:55)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyuserslist -->
      </class> <!-- assertions.AssertionClass -->
      <class name="annotation.AnnotationInTestNGTwo">
        <test-method signature="sampleBMethodFromAnnotationInTestNGTwo()[pri:0, instance:annotation.AnnotationInTestNGTwo@3e7dd664]" started-at="2024-10-12T13:52:28Z" name="sampleBMethodFromAnnotationInTestNGTwo" finished-at="2024-10-12T13:52:28Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleBMethodFromAnnotationInTestNGTwo -->
        <test-method signature="sampleAMethodFromAnnotationInTestNGTwo()[pri:0, instance:annotation.AnnotationInTestNGTwo@3e7dd664]" started-at="2024-10-12T13:52:28Z" name="sampleAMethodFromAnnotationInTestNGTwo" finished-at="2024-10-12T13:52:28Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleAMethodFromAnnotationInTestNGTwo -->
      </class> <!-- annotation.AnnotationInTestNGTwo -->
      <class name="brockenlink.BrockenLinkClass3ToolQA">
        <test-method signature="sampleTestCase()[pri:0, instance:brockenlink.BrockenLinkClass3ToolQA@3568f9d2]" started-at="2024-10-12T13:51:15Z" name="sampleTestCase" finished-at="2024-10-12T13:52:23Z" duration-ms="67708" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleTestCase -->
      </class> <!-- brockenlink.BrockenLinkClass3ToolQA -->
      <class name="data_provider_annotation.DataProviderClass2">
        <test-method signature="verifyUserCanLoginWithProvidedCredentials2(java.lang.String, java.lang.String)[pri:0, instance:data_provider_annotation.DataProviderClass2@5143c662]" started-at="2024-10-12T13:48:24Z" name="verifyUserCanLoginWithProvidedCredentials2" data-provider="pair" finished-at="2024-10-12T13:48:24Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.xssf.usermodel.XSSFSheet.getLastRowNum()" because "this.sh" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "org.apache.poi.xssf.usermodel.XSSFSheet.getLastRowNum()" because "this.sh" is null
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:131)
at org.testng.internal.Parameters.handleParameters(Parameters.java:706)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:923)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.poi.xssf.usermodel.XSSFSheet.getLastRowNum()" because "this.sh" is null
at helper.ExcelHelper.getKeysList(ExcelHelper.java:40)
at data_provider_annotation.DataProviderClass2.sendUserCredentials(DataProviderClass2.java:18)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
... 22 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserCanLoginWithProvidedCredentials2 -->
      </class> <!-- data_provider_annotation.DataProviderClass2 -->
      <class name="brockenlink.BrockenLinkClass4ToolQA2">
        <test-method signature="sampleTestCase()[pri:0, instance:brockenlink.BrockenLinkClass4ToolQA2@403f0a22]" started-at="2024-10-12T13:45:02Z" name="sampleTestCase" finished-at="2024-10-12T13:48:20Z" duration-ms="198261" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleTestCase -->
      </class> <!-- brockenlink.BrockenLinkClass4ToolQA2 -->
      <class name="brockenlink.BrockenLinkClass5ToolQA3">
        <test-method signature="verifyLinksAreBrockenOrNot()[pri:0, instance:brockenlink.BrockenLinkClass5ToolQA3@3da30852]" started-at="2024-10-12T13:42:52Z" name="verifyLinksAreBrockenOrNot" finished-at="2024-10-12T13:45:02Z" duration-ms="130127" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLinksAreBrockenOrNot -->
      </class> <!-- brockenlink.BrockenLinkClass5ToolQA3 -->
      <class name="screen.cpature.ScreenCaptureClass">
        <test-method signature="sampleTestCase()[pri:0, instance:screen.cpature.ScreenCaptureClass@6995bf68]" started-at="2024-10-12T13:48:20Z" name="sampleTestCase" finished-at="2024-10-12T13:48:24Z" duration-ms="3550" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleTestCase -->
      </class> <!-- screen.cpature.ScreenCaptureClass -->
      <class name="dependent.Depedent_test_case_class">
        <test-method signature="verifyUserCanLoginWithValidusernameandPassward()[pri:0, instance:dependent.Depedent_test_case_class@40238dd0]" started-at="2024-10-12T13:40:56Z" name="verifyUserCanLoginWithValidusernameandPassward" finished-at="2024-10-12T13:40:56Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserCanLoginWithValidusernameandPassward -->
        <test-method signature="VerifyUserCanSendEmail()[pri:0, instance:dependent.Depedent_test_case_class@40238dd0]" started-at="2024-10-12T13:40:56Z" name="VerifyUserCanSendEmail" finished-at="2024-10-12T13:40:56Z" depends-on-methods="dependent.Depedent_test_case_class.verifyUserCanLoginWithValidusernameandPassward" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at dependent.Depedent_test_case_class.VerifyUserCanSendEmail(Depedent_test_case_class.java:17)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyUserCanSendEmail -->
        <test-method signature="VerifyUserCanReadEmail()[pri:0, instance:dependent.Depedent_test_case_class@40238dd0]" started-at="2024-10-12T13:40:56Z" name="VerifyUserCanReadEmail" finished-at="2024-10-12T13:40:56Z" depends-on-methods="dependent.Depedent_test_case_class.VerifyUserCanSendEmail" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Depedent_test_case_class.VerifyUserCanReadEmail()[pri:0, instance:dependent.Depedent_test_case_class@40238dd0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Depedent_test_case_class.VerifyUserCanReadEmail()[pri:0, instance:dependent.Depedent_test_case_class@40238dd0] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyUserCanReadEmail -->
      </class> <!-- dependent.Depedent_test_case_class -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
